name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up build environment
      run: sudo apt-get update && sudo apt-get install -y gcc cppcheck valgrind

    - name: Compile with make
      run: make

    - name: Run tests with Valgrind
      run: make valgrind

    - name: Run Cppcheck analysis
      run: make cppcheck
